# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-06 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('parameter', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, default=0)),
                ('pregnancies', models.IntegerField(blank=True, default=0)),
                ('glucose', models.IntegerField(blank=True, default=0)),
                ('insulin', models.IntegerField(blank=True, default=0)),
                ('blood_pressure', models.IntegerField(blank=True, default=0)),
                ('skin_thickness', models.IntegerField(blank=True, default=0)),
                ('bmi', models.FloatField(blank=True, default=0.0)),
                ('diabetes_predigree_function', models.FloatField(blank=True, default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(blank=True, default='', max_length=20)),
                ('first_name', models.CharField(blank=True, default='', max_length=30)),
                ('last_name', models.CharField(blank=True, default='', max_length=30)),
                ('gender', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.CharField(blank=True, default='', max_length=50)),
                ('password', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(blank=True, default='', max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('measurement', models.CharField(blank=True, default='', max_length=1000)),
                ('prediction', models.CharField(blank=True, default='', max_length=1000)),
                ('suggestion', models.CharField(blank=True, default='', max_length=1000)),
                ('comments', models.CharField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='measurement',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='capstoneapp.Patient'),
        ),
    ]
