# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-07 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0002_auto_20170406_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='heartbeat',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='measurement',
            name='height',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='measurement',
            name='weight',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
