# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-18 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0003_auto_20170407_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='patient',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, to='capstoneapp.Patient'),
            preserve_default=False,
        ),
    ]
